config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  username == 'admin' && password == 'qwerty'
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/async/tasks'

  # Base
  root to: 'welcome#islands'
  get '/index' => 'welcome#index'
  get '/page_404' => 'welcome#page_404', as: :page_404

  get '/articles' => 'welcome#legacy_articles'
  get '/search'   => 'welcome#legacy_search'

  get '/new',  to: redirect('/', status: 301) # 410
  get '/news', to: redirect('/', status: 301)

  get '/authors_articles', to: redirect('/', status: 301)
  get '/blogs.rss', to: redirect('/rss.rss',  status: 301)
  get '/archive',   to: redirect('/archive_numbers', status: 301)
  get '/archives',  to: redirect('/archive_numbers', status: 301)
  get '/partners',  to: redirect('/pages/partners',  status: 301)

  get '/hubs/future', to: redirect('/hubs/future-future', status: 301)

  get '/materia',  to: redirect('http://artelectronics.ru/posts/myslyaschaya-materiya', status: 301)
  get '/materiya', to: redirect('http://artelectronics.ru/posts/myslyaschaya-materiya', status: 301)

  # XML feeds
  get '/feedly.rss'        => 'welcome#feedly',      defaults: { format: :rss }
  get '/novoteka.rss'      => 'welcome#novoteka',      defaults: { format: :rss }
  get '/yandex.rss'        => 'welcome#yandex',        defaults: { format: :rss }
  get '/rss.rss'           => 'welcome#rss',           defaults: { format: :rss }
  get '/rss_full.rss'      => 'welcome#rss_full',      defaults: { format: :rss }
  get '/telegraf_full.rss' => 'welcome#telegraf_full', defaults: { format: :rss }
  get '/rambler.rss'       => 'welcome#rambler',       defaults: { format: :rss }
  get '/surfingbird.rss'   => 'welcome#surfingbird',   defaults: { format: :rss }

  get '/flipboard_culture.rss' => 'welcome#flipboard_culture', defaults: { format: :rss }
  get '/flipboard_tech.rss'    => 'welcome#flipboard_tech',    defaults: { format: :rss }

  get '/sitemap.xml'       => 'welcome#sitemap',       defaults: { format: :xml }

  # Login system
  devise_for :users, path: '',
    :path_names => {
      sign_in:  'login',
      sign_up:  'signup',
      sign_out: 'logout'
    },
    :controllers => {
      :omniauth_callbacks => "omniauth_callbacks",
      :confirmations      => "confirmations",
      :registrations      => "registrations",
      :sessions           => "sessions",
      :passwords          => "passwords"
    }

  devise_scope :user do
    get '/account_should_be_activate' => 'registrations#account_should_be_activate'
  end

  # Personal
  get "cabinet" => "users#cabinet", as: :cabinet

  # Search
  match "search/:squery" => "search#index", via: %w[ get post ], as: :qsearch

  # Special Posts
  post '/tatlin_postcard' => 'special_posts#tatlin_postcard'

  %w[ authors archive_numbers ].each do |model|
    resources model do
      collection do
        get :manage
      end
    end
  end

  get '/authors/:id' => 'authors#show', constraints: {:id => /[^\/]+/}
  get "authors/by/:letter" => "authors#by_letter", as: :author_by_letter

  resources :meta_data

  TheAudit::Routes.mixin(self)
  TheBanners::Routes.mixin(self)

  # Subscribers
  post "subscribers/add" => "subscribers#add", as: :add_subscriber

  namespace :admin do
    TheRole::Routes.mixin(self)
  end

  # TheComments
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]

  concern :sortable_tree do
    collection do
      get  :manage
      post :rebuild
    end
  end

  # legacy url
  get '/blogs/:id' => 'welcome#legacy_blog', constraints: { id: /\d{1,3}/ }

  # Direct routes
  %w{ hubs pages posts blogs }.each do |name|
    resources name, concerns: :sortable_tree do
      get :print

      member do
        patch  :main_image_crop_270x210
        patch  :main_image_crop_100x100
        patch  :main_image_rotate
        delete :main_image_delete
      end
    end
  end

  resources :hubs do
    post :expand_node, on: :collection
  end

  # Users
  resources :users, only: %w[ index show edit update ] do
    patch  :change_email
    patch  :change_password

    patch  :avatar_crop
    delete :avatar_delete

    %w[ hubs pages posts blogs ].each do |name|
      resources name, concerns: :sortable_tree do
        get :my, on: :collection
      end
    end
  end

  # tags
  # tags
  get "tag/:tag" => "tags#show", as: :tag

  # /users/:user_id/manage/posts
  get "manage/:pub_type" => 'posts#manage', as: :pubs_manage
  get "users/:user_id/manage/:pub_type" => 'posts#manage', as: :user_pubs_manage
  get "/:id" => 'hubs#system_section', as: :system_hub

  # Mailer
  get '/rails/mailers' => "rails/mailers#index"
  get '/rails/mailers/*path' => "rails/mailers#preview"

  # Legacy Urls
  get '/:c_slug/:s_slug/:id' => 'welcome#legacy_post'
  get '/:c_slug/:s_slug'     => 'welcome#legacy_hub'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
    :confirmable,
    :recoverable,
    :validatable,
    :registerable,
    :rememberable,
    :omniauthable,
    :omniauth_providers => %w[ facebook twitter vkontakte google_oauth2 ]

  include UserAvatar
  include HasMetaData
  include TheRole::User

  include TheSimpleSort::Base
  include ThePagination::Base

  include TheComments::User
  include TheComments::Commentable

  include ActAsStorage
  include HasAttachedFiles

  include SocialNetworksLogin
  include UserSoialNetworksValidation
  include TheNotification::LocalizedErrors

  before_validation :create_default_login, on: :create
  before_validation :prepare_login

  def to_param; self.login end

  # Relations
  has_many :hubs
  has_many :pages
  has_many :posts
  has_many :blogs
  has_one  :author, validate: true, dependent: :nullify

  # Validations
  validates :login, presence: true, uniqueness: true
  validate  :login_chars_required

  def login_chars_required
    errors.add(:login, "должен содержать хотя бы один символ") unless (self.login =~ /[a-zA-Z]/mix)
  end

  class << self
    def root
      @@root ||= User.first
    end
  end

  def admin?
    self == User.root
  end

  # TheComments methods
  def comments_admin?
    self == User.root
  end

  def comments_moderator? comment
    admin? || id == comment.holder_id
  end

  def commentable_title
    login
  end

  def commentable_path
    [self.class.to_s.tableize, login].join('/')
  end
  # ~ TheComments methods

  def role_name
    role.try(:name)
  end

  def recalculate_all_attached_files!
    # Recalculate all user counters here
  end

  # Select an available hubs
  #
  # Admin has: all + for_manage hubs
  #
  # Any User has: hubs defined in his TheRole
  # with section "available_hubs"
  def available_hubs object = nil
    return Hub.none if object.nil?

    ctrl_name = object.ctrl_name                        # posts
    scope = ctrl_name.blank? ? :all : [:of_, ctrl_name] # [:of_, :posts]

    return Hub.send(*scope).for_manage if admin?        # Hub.of_posts

    section = role.to_hash.try(:[], 'available_hubs')
    return Hub.none if section.blank?

    keys = section.select{|k, v| v == true }.keys
    keys.map!{|item| item.to_slug_param }

    Hub.friendly_where(keys).published_set.send(*scope)
  end

  # articles, blogs, pages
  def editable_hubs_for section_name = nil
    return Hub.none unless section_name

    top_hub = Hub.where(slug: section_name).first
    return Hub.none unless top_hub

    pub_scope = admin? ? :published : :all
    top_hub.self_and_descendants.send(pub_scope)
  end

  private

  def create_default_login
    _login = "user-#{ SecureRandom.hex[0..4] }"
    self.login = self.login.blank? ? _login : self.login
  end

  def prepare_login
    self.login = self.login.to_s.to_slug_param
  end

  def calculate_signup_fields!
    self.role = Role.with_name(:blogger) if self.role.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # STATUS: DONE

  layout 'bootstrap_default', only: %w[ index cabinet show edit update change_email ]

  before_action :set_user, only: %w[
    show edit update
    avatar_crop avatar_delete
    change_password change_email
  ]

  before_action :user_require,   except: %w[ index show new ]
  before_action :role_required,  except: %w[ index show new ]
  before_action :owner_required, except: %w[ index show new cabinet ]

  # Public actions

  def index
    @users = User.includes(:role).order("role_id ASC").simple_sort(params).pagination(params)
  end

  def cabinet; end

  def new; @user = User.new ; end

  # Restricted actions

  def show; end

  def edit
    @authors = Author.pluck(:name, :id)
  end

  def update
    if @user.update(user_params)
      @user.author = Author.find(params[:user][:author])
      redirect_to url_for([:edit, @user]), notice: "Изменения сохранены"
    else
      @user.reload
      render 'users/edit'
    end
  end

  def avatar_crop
    path = @user.avatar_crop(params)
    render json: { ids: { avatar_medium: path } }
  end

  def avatar_delete
    @user.avatar = nil
    @user.save
    redirect_back notice: "Изображение удалено"
  end

  def change_password
    @user.send_reset_password_instructions
    redirect_to url_for([:edit, @user]), notice: "В течение нескольких минут вы получите письмо с инструкциями по смене пароле"
  end

  def change_email
    if @user.update(user_params)
      redirect_to url_for([:edit, @user]), notice: "В течение нескольких минут вы получите письмо с инструкциями по подтверждению вашего нового Email."
    else
      @user.reload
      render 'users/edit'
    end
  end

  private

  def set_user
    @user = User.where(login: user_id).first
    @owner_check_object = @user
  end

  def user_id
    params[:id] || params[:user_id]
  end

  def user_params
    params.require(:user).permit(
      :avatar, :login, :username, :email, :raw_about,
      :vk_addr, :tw_addr, :fb_addr, :ig_addr, :pt_addr, :gp_addr
    )
  end
end

app/views/bootstrap_default/users/_change_role.html.haml
- if current_user && current_user.has_role?(:roles, :update)
  .collapse.navbar-collapse.pull-right
    %ul.nav.navbar-nav
      %li.dropdown
        %a.dropdown-toggle{ href: '#',  data: { toggle: :dropdown } }
          Change Role:
          %b.caret
        %ul.dropdown-menu.alert-info
          - Role.all.each do |role|
            %li= link_to role.title, '#'

app/views/bootstrap_default/users/_form.html.slim
= render partial: 'the_crop/canvas', locals: { image: @user.avatar.url(:original) }
= render partial: 'the_notification/form', locals: { object: @user, format: :json }

.panel.panel-default
  .panel-heading
    h3 Основная информация
  .panel-body
    = form_for @user, html: { enctype: "multipart/form-data", role: :form } do |f|
      .form-group
        p= image_tag current_user.avatar.url(:medium), id: :avatar_medium
        p
          = f.file_field :avatar, class: 'btn btn-default', style: 'display:inline'
          - if @user.avatar?
            ruby:
              crop_data_150_150 = {
                url: user_avatar_crop_path(@user),
                source:  @user.avatar.url(:original),
                holder:  { width: 400 },
                preview: { width: 100, height: 100 },
                final_size: "100x100",
                callback_handler: "TheCrop.post_main_image_crop"
              }

            '
            = link_to "Изменить миниатюру", "#", class: "btn btn-success js_the_crop", data: crop_data_150_150
            '
            = link_to "Удалить миниатюру", user_avatar_delete_path(@user), method: :delete, class: "btn btn-danger"

      .form-group
        = f.label :username, "Имя пользователя"
        = f.text_field :username, class: 'form-control'

      .form-group
        .row
          .col-md-12= f.label :author, 'Автор:'
        .row
          - @authors = [['-', nil]] + @authors
          - options = options_for_select(@authors, (@user.author.id if @user.author))
          .col-md-12= f.select :author, options, {}, autocomplete: :off, class: 'form-control input-medium'

      .form-group
        = f.label :raw_about, "О себе"
        = f.text_area :raw_about, class: 'form-control', style: 'height: 200px;'

      .form-group
        = f.submit "Обновить профиль", class: 'btn btn-info'

.panel.panel-default
  .panel-heading
    h3 Социальные сети
  .panel-body
    = form_for @user, html: { role: :form } do |f|
      .form-group
        = f.label :fb_addr, "facebook.com"
        = f.text_field :fb_addr, class: 'form-control'

      .form-group
        = f.label :vk_addr, "vk.com"
        = f.text_field :vk_addr, class: 'form-control'

      .form-group
        = f.label :tw_addr, "twitter.com"
        = f.text_field :tw_addr, class: 'form-control'

      .form-group
        = f.label :ig_addr, "instagram.com"
        = f.text_field :ig_addr, class: 'form-control'

      .form-group
        = f.label :pt_addr, "pinterest.com"
        = f.text_field :pt_addr, class: 'form-control'

      .form-group
        = f.label :gp_addr, "google plus"
        = f.text_field :gp_addr, class: 'form-control'

      .form-group
        = f.submit "Обновить профиль", class: 'btn btn-info'

.panel.panel-default
  .panel-heading
    h3 Сменить Email
  .panel-body
    p Для того, что бы новый Email вступил в силу, вам будет необходимо подтвердить его, перейдя по ссылке, которая будет вам выслана на желаемый Email

    = form_for @user, url: user_change_email_path(@user), method: :patch, html: { role: :form } do |f|
      .form-group
        = f.label :email, "Укажите ваш новый email"
        = f.text_field :email, class: 'form-control'

      - if @user.unconfirmed_email
        .form-group
          b Email ожидает подтверждения:
          '
          = @user.unconfirmed_email

      .form-group
        = f.submit "Сменить Email", class: 'btn btn-info'

.panel.panel-default
  .panel-heading
    h3 Сменить логин
  .panel-body
    p Логин - ваш псевдоним в системе. Смена логина может отразиться на доступности публикаций, в адресе которых он используется.
    = form_for @user, html: { role: :form } do |f|
      .form-group
        = f.label :login, "Логин"
        = f.text_field :login, class: 'form-control'
      .form-group
        = f.submit "Обновить профиль", class: 'btn btn-info', data: { confirm: "Я уверен, что хочу сменить Логин" }

.panel.panel-default
  .panel-heading
    h3 Сменить пароль
  .panel-body
    p Инструкции по процессу смены пароля вам будут высланы на ваш текущий Email.
    = link_to "Сменить пароль", user_change_password_path(@user), method: :patch, class: 'btn btn-warning'

- credentials = @user.credentials
- if credentials.size < 4
  .sessions.new
    .panel.panel-default
      .panel-heading
        h3 Привязать аккаунт к социальным сетям

      .panel-body
        p Привязка к социальным сетям позволит вам выполнять легкий вход на сайт без ввода Email и пароля.
        p <b>Обратите внимание</b>, что регистрация с помощью различных социальных сетей приводит к созданию различных аккаунтов на сайте ArtElectronics.ru.
        p Если вы хотите <b>входить в один и тот же аккаунт</b> с помощью различных социальных сетей, то выполните привязку своего аккаунта к социальным сетям с этой страницы с помощью следующих кнопок:

        .social_login style='text-align:left'
          - if credentials.select{|c| c.provider == 'vkontakte'}.blank?
            = link_to '', user_omniauth_authorize_path(:vkontakte),     class: :vk
          - if credentials.select{|c| c.provider == 'facebook'}.blank?
            = link_to '', user_omniauth_authorize_path(:facebook),      class: :fb
          - if credentials.select{|c| c.provider == 'twitter'}.blank?
            = link_to '', user_omniauth_authorize_path(:twitter),       class: :tw
          - if credentials.select{|c| c.provider == 'google_oauth2'}.blank?
            = link_to '', user_omniauth_authorize_path(:google_oauth2), class: :gp

          = form_for(@user, as: @user.class, url: registration_path(@user), html: { id: :signin, class: :hidden, remote: true, data: { type: :json } }) do |f|
            = hidden_field_tag 'user[oauth_data]', '', id: :oauth_data, autocomplete: :off

- if credentials.any?
  br
  .panel.panel-default
    .panel-heading
      h4 Ваш аккаунт уже привязан к социальным сетям
    .panel-body
      ol
        - @user.credentials.each do |credential|
          li
            b= credential.provider

app/views/bootstrap_default/users/cabinet.html.haml
- content_for :sidebar do
  .panel.panel-default
    .panel-heading
      %b Логин:
      = @user.login

    .panel-body
      %p
        = image_tag @user.avatar.url(:medium)
      %p
        %b Имя:
        = @user.username

      %p
        %b Email:
        = @user.email

      - if (credentials = @user.credentials).any?
        %p
          %b Привязано к:
        %ul
          - credentials.each do |credential|
            %li= credential.provider

      %br
      %p= link_to "Редактировать", edit_user_url(@user), class: 'btn btn-info'

%h3= t ".cabinet", login: @user.login

- if current_user.any_role?(posts: :new, pages: :new, blogs: :new)
  %h4= t '.create'
  %br

  %p
    - %w[ posts pages blogs ].each do |model_name|
      - if current_user.has_role?(model_name, :new)
        = link_to t(:new, scope: model_name), [:new, model_name.singularize], class: 'btn btn-primary', style: 'margin-right: 30px;'

  %br

- if current_user.any_role?(posts: :my, blogs: :my, pages: :my)
  %h4 Мои публикации (управление):

  .list-group
    - %w[ posts pages blogs ].each do |model_name|
      - if current_user.has_role?(model_name, :my)
        = link_to [:my, @user, model_name], class: 'list-group-item' do
          = t(".my_#{ model_name }")
          %span.badge.alert-info
            Черновики:
            = @user.send(model_name).with_state(:draft).count
          %span.badge.alert-success
            Опубликовано:
            = @user.send(model_name).with_state(:published).count

- if current_user.any_role?(posts: :my, blogs: :my, pages: :my)
  %h4 Мои публикации (просмотр):

  .list-group
    - %w[ posts pages blogs ].each do |model_name|
      - if current_user.has_role?(model_name, :my)
        = link_to [@user, model_name], class: 'list-group-item' do
          = t(:my, scope: [model_name])
          %span.badge.alert-success
            Опубликовано:
            = @user.send(model_name).with_state(:published).count

- if current_user.any_role?(moderator: :posts, moderator: :pages, moderator: :blogs)
  %h4 Управление публикациями сайта:

  .list-group
    - %w[ posts pages blogs ].each do |model_name|
      - if current_user.has_role?(model_name, :manage)
        = link_to [:manage, model_name], class: 'list-group-item' do
          = t("#{ model_name }.manage")
          %span.badge.alert-info
            Черновики:
            = model_name.classify.constantize.with_state(:draft).count
          %span.badge.alert-success
            Опубликовано:
            = model_name.classify.constantize.with_state(:published).count

- if @user.has_role?(:comments, :manage)
  %h4= t '.comments'
  .list-group
    = link_to [:manage, :comments], class: 'list-group-item' do
      = t '.comments'

      %span.badge.alert-warning
        На модерации:
        = @user.draft_comcoms_count

      %span.badge.alert-info
        Написано к моим постам:
        = @user.comcoms.active.count

      %span.badge.alert-success
        Написано мной:
        = @user.my_comments.active.count

- if @user.has_role?(:hubs, :manage)
  %h4= t '.hubs_manage'

  .list-group
    = link_to t('.hubs'), manage_hubs_url, class: 'list-group-item'

- if current_user.has_role?(:meta_data, :manage)
  %h4 SEO:

  .list-group
    - if current_user.has_role?(:meta_data, :manage)
      = link_to "SEO. Мета данные", meta_data_url, class: 'list-group-item'

- if @user.has_role?(:author, :manage)
  %h4= t '.authors'

  .list-group
    = link_to t('.authors_list'), manage_authors_url, class: 'list-group-item'

- if @user.has_role?(:banners, :manage)
  %h4 Баннеры

  .list-group
    = link_to t('.banners'), banners_path, class: 'list-group-item'

- if @user.any_role?(users: :manage, roles: :manage)
  %h4= t '.users_and_roles'

  .list-group
    = link_to t('.users'), users_url, class: 'list-group-item'
    = link_to t('.roles'), admin_roles_url, class: 'list-group-item'

- if @user.has_role?(:archives, :manage)
  %h4= t '.archive'
  .list-group
    = link_to t('.numbers'), manage_archive_numbers_path, class: 'list-group-item'

  %h4 Аудит:
  .list-group
    = link_to 'Аудит', audits_path, class: 'list-group-item'

app/views/bootstrap_default/users/edit.html.slim
- content_for :express_nav do
  p= link_to t('app.cabinet'), cabinet_url
  p= link_to "Моя страница", url_for(@user)

h1 Редактировать профиль
br
= render 'users/form'

app/views/bootstrap_default/users/index.html.haml
- content_for :full_width do
  = paginate @users

  %table.table.table-striped.table-hover
    %thead
      %tr
        %th
        %th= link_to 'Логин ↕', simple_sort_url(:login, params), title: :login
        %th= link_to 'Имя пользователя ↕',  simple_sort_url(:username,  params), title: :username
        %th= link_to 'Зарегистрирован ↕', simple_sort_url(:created_at,  params), title: :created_at
        - if current_user && current_user.admin?
          %th Действия

    %tbody
      - @users.each do |user|
        %tr
          %td= image_tag user.avatar.url(:thumb)
          %td= user.login
          %td= user.username
          %td= I18n.l(user.created_at, format: "%-d %B %Y")
          - if current_user && current_user.admin?
            %td
              %p= link_to 'Правка', edit_user_path(user)

  = paginate @users

app/views/bootstrap_default/users/show.html.haml
%h2
  = image_tag @user.avatar.url(:medium)

  - if @user.username.present?
    = @user.username
  - else
    = @user.login
%br

%h4 Логин: #{ @user.login }
%p Роль пользователя на сайте: #{ @user.role.name }

%hr