config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  username == 'admin' && password == 'qwerty'
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/async/tasks'

  # Base
  root to: 'welcome#islands'
  get '/index' => 'welcome#index'
  get '/page_404' => 'welcome#page_404', as: :page_404

  get '/articles' => 'welcome#legacy_articles'
  get '/search'   => 'welcome#legacy_search'

  get '/new',  to: redirect('/', status: 301) # 410
  get '/news', to: redirect('/', status: 301)

  get '/authors_articles', to: redirect('/', status: 301)
  get '/blogs.rss', to: redirect('/rss.rss',  status: 301)
  get '/archive',   to: redirect('/archive_numbers', status: 301)
  get '/archives',  to: redirect('/archive_numbers', status: 301)
  get '/partners',  to: redirect('/pages/partners',  status: 301)

  get '/hubs/future', to: redirect('/hubs/future-future', status: 301)

  get '/materia',  to: redirect('http://artelectronics.ru/posts/myslyaschaya-materiya', status: 301)
  get '/materiya', to: redirect('http://artelectronics.ru/posts/myslyaschaya-materiya', status: 301)

  # XML feeds
  get '/feedly.rss'        => 'welcome#feedly',      defaults: { format: :rss }
  get '/novoteka.rss'      => 'welcome#novoteka',      defaults: { format: :rss }
  get '/yandex.rss'        => 'welcome#yandex',        defaults: { format: :rss }
  get '/rss.rss'           => 'welcome#rss',           defaults: { format: :rss }
  get '/rss_full.rss'      => 'welcome#rss_full',      defaults: { format: :rss }
  get '/telegraf_full.rss' => 'welcome#telegraf_full', defaults: { format: :rss }
  get '/rambler.rss'       => 'welcome#rambler',       defaults: { format: :rss }
  get '/surfingbird.rss'   => 'welcome#surfingbird',   defaults: { format: :rss }

  get '/flipboard_culture.rss' => 'welcome#flipboard_culture', defaults: { format: :rss }
  get '/flipboard_tech.rss'    => 'welcome#flipboard_tech',    defaults: { format: :rss }

  get '/sitemap.xml'       => 'welcome#sitemap',       defaults: { format: :xml }

  # Login system
  devise_for :users, path: '',
    :path_names => {
      sign_in:  'login',
      sign_up:  'signup',
      sign_out: 'logout'
    },
    :controllers => {
      :omniauth_callbacks => "omniauth_callbacks",
      :confirmations      => "confirmations",
      :registrations      => "registrations",
      :sessions           => "sessions",
      :passwords          => "passwords"
    }

  devise_scope :user do
    get '/account_should_be_activate' => 'registrations#account_should_be_activate'
  end

  # Personal
  get "cabinet" => "users#cabinet", as: :cabinet

  # Search
  match "search/:squery" => "search#index", via: %w[ get post ], as: :qsearch

  # Special Posts
  post '/tatlin_postcard' => 'special_posts#tatlin_postcard'

  %w[ authors archive_numbers ].each do |model|
    resources model do
      collection do
        get :manage
      end
    end
  end

  get '/authors/:id' => 'authors#show', constraints: {:id => /[^\/]+/}
  get "authors/by/:letter" => "authors#by_letter", as: :author_by_letter

  resources :meta_data

  TheAudit::Routes.mixin(self)
  TheBanners::Routes.mixin(self)

  # Subscribers
  post "subscribers/add" => "subscribers#add", as: :add_subscriber

  namespace :admin do
    TheRole::Routes.mixin(self)
  end

  # TheComments
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]

  concern :sortable_tree do
    collection do
      get  :manage
      post :rebuild
    end
  end

  # legacy url
  get '/blogs/:id' => 'welcome#legacy_blog', constraints: { id: /\d{1,3}/ }

  # Direct routes
  %w{ hubs pages posts blogs }.each do |name|
    resources name, concerns: :sortable_tree do
      get :print

      member do
        patch  :main_image_crop_270x210
        patch  :main_image_crop_100x100
        patch  :main_image_rotate
        delete :main_image_delete
      end
    end
  end

  resources :hubs do
    post :expand_node, on: :collection
  end

  # Users
  resources :users, only: %w[ index show edit update ] do
    patch  :change_email
    patch  :change_password

    patch  :avatar_crop
    delete :avatar_delete

    %w[ hubs pages posts blogs ].each do |name|
      resources name, concerns: :sortable_tree do
        get :my, on: :collection
      end
    end
  end

  # tags
  # tags
  get "tag/:tag" => "tags#show", as: :tag

  # /users/:user_id/manage/posts
  get "manage/:pub_type" => 'posts#manage', as: :pubs_manage
  get "users/:user_id/manage/:pub_type" => 'posts#manage', as: :user_pubs_manage
  get "/:id" => 'hubs#system_section', as: :system_hub

  # Mailer
  get '/rails/mailers' => "rails/mailers#index"
  get '/rails/mailers/*path' => "rails/mailers#preview"

  # Legacy Urls
  get '/:c_slug/:s_slug/:id' => 'welcome#legacy_post'
  get '/:c_slug/:s_slug'     => 'welcome#legacy_hub'
end

app/models/author.rb
class Author < ActiveRecord::Base
  include HasMetaData
  def to_param; name; end

  has_attached_file :avatar,
                    styles: { :small => "90x90#", :big => "150x150#" },
                    default_url: "/default_images/author/avatar/:style/missing.jpg",
                    path: ":rails_root/public/uploads/storages/author/:id/avatar/:style/:id.:extension",
                    url: "/uploads/storages/author/:id/avatar/:style/:id.:extension"

    # :url => "/system/:class/:style/:id.:extension",
    # :path => "#{RAILS_ROOT}/public/system/:class/:style/:id.:extension"
  do_not_validate_attachment_file_type :avatar

  before_validation :define_first_letter

  # relations
  has_many   :authorships
  has_many   :posts, through: :authorships
  belongs_to :user

  # validation
  validates :name,        presence: true
  validates :description, presence: true

  scope :by_letter, ->(letter) { where("first_letter LIKE ?", "#{ letter }%") }

  def self.alphabet
    en, ru = Author.pluck(:first_letter).map{|item| item.mb_chars.downcase.to_s }.uniq.sort.map(&:ord).inject([ [], [] ]) do |res, item|
      res.first.push(item) if item < 1000
      res.last.push(item)  if item >= 1000
      res
    end

    [ en.uniq.map(&:chr), ru.uniq.map(&:chr) ]
  end

  private

  def define_first_letter
    return true if self.first_letter.present?
    self.first_letter = self.name.split(' ').last.first.mb_chars.upcase.to_s
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  layout 'bootstrap_default', except: %w[ index show by_letter ]

  before_action :set_author, only: %w[ show edit update destroy ]

  before_action :user_require,  except: %w[ index show by_letter ]
  before_action :role_required, except: %w[ index show by_letter ]

  def index
    @authors = Author.all.page params[:page]
  end

  def show; end

  def by_letter
    @authors = Author.by_letter(params[:letter]).page params[:page]
    render template: 'authors/index'
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to url_for(@author), notice: t('authors.created')
    else
      render action: 'new'
    end
  end

  def update
    if @author.update(author_params)
      redirect_to url_for([:edit, @author]), notice: t('authors.updated')
    else
      render action: 'edit'
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_url
  end

  def manage
    @authors = Author.all.page params[:page]
  end

  private
    def set_author
      @author = Author.where(id: params[:id]).first || Author.where(name: params[:id]).first
    end

    def author_params
      params.require(:author).permit(
        :name,
        :avatar,

        :user_id,
        :first_letter,

        :description,
        :short_description
      )
    end
end

app/views/bootstrap_default/authors/_form.html.haml
= render partial: 'publications/editor'

= form_for(@author) do |f|
  = render partial: 'the_notification/form', locals: { object: @author }

  .form-group
    = image_tag @author.avatar.url, width: 150

  .form-group
    = f.label :avatar, t('authors.avatar')
    = f.file_field :avatar

  .form-group
    = f.label :first_letter, 'Буква в списке'
    = f.text_field :first_letter, class: 'form-control', maxlength: 1, style: 'width:70px;text-transform:uppercase'

  .form-group
    = f.label :user_id, 'Привязанный пользователь'
    - options = options_for_select(User.all.map{|u| [ "#{ u.id } => #{ u.username }" , u.id ] }, @author.user_id)
    = f.select :user_id, options, { include_blank: true }, autocomplete: :off, class: 'form-control input-medium'

  .form-group
    = f.label :name, t('authors.name')
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :short_description, t('authors.short_description')
    = f.text_area :short_description, class: :redactor_content, id: :redactor_intro

  .form-group
    = f.label :description, t('authors.description')
    = f.text_area :description, class: :redactor_content, id: :redactor_content

  .form-group
    = f.submit t('authors.save'), class: 'btn btn-info'

app/views/bootstrap_default/authors/edit.html.haml
- content_for :express_nav do
  %p= link_to t('authors.show'), @author
  %p= link_to t('authors.lenta'), authors_path

%h1= t('authors.edit')
= render 'form'

app/views/bootstrap_default/authors/manage.html.haml
/ - content_for :express_nav do
/   %p= link_to t('authors.lenta'), authors_path

- content_for :authors do
  %h1= t('authors.list')

  %li= link_to(t('authors.new'), new_author_path)

  = paginate @authors

  %table.table.table-striped.table-hover
    %thead
      %tr
        %th= t('authors.name')
        %th= t('authors.short_description')
        / %th= t('authors.created_at')
        %th Действия

    %tbody
      - @authors.each do |author|
        %tr
          %td
            = image_tag author.avatar.url :small
          %td
            %p
              %b= link_to author.name, author
            = raw author.short_description
          / %td= author.created_at.strftime('%d.%m.%Y')

          - if current_user.try(:admin?)
            %td
              %p= link_to 'Просмотр', author, title: 'Просмотр'
              %p= link_to 'Правка', edit_author_path(author), title: 'Правка'
              %p= link_to 'Удалить', author, method: :delete, data: { confirm: 'Вы точно хотите удалить Автора?' },  title: 'Удалить автора'

  = paginate @authors

app/views/bootstrap_default/authors/new.html.haml
- content_for :express_nav do
  / %p= link_to t('authors.manage'), authors_manage_path
  %p= link_to t('authors.lenta'), authors_path

%h1= t('authors.new')
= render('form')

app/views/bootstrap_default/authors/show.html.haml
- if current_user.try(:admin?)
  - content_for :express_nav do
    %p= link_to t('authors.edit'), edit_author_path(@author)
    %p= link_to t('authors.manage'), manage_authors_path
    %p= link_to t('authors.lenta'), authors_path

%h1= t('authors.show')

%table.table
  %tbody
    %tr
      %td
      %td
        = image_tag @author.avatar.url :big
    %tr
      %td
        %strong= t('authors.name')
      %td
        %strong= @author.name
    %tr
      %td
        %strong= t('authors.short_description')
      %td
        = raw @author.short_description
    %tr
      %td
        %strong= t('authors.description')
      %td
        = raw @author.description