config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  username == 'admin' && password == 'qwerty'
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/async/tasks'

  # Base
  root to: 'welcome#islands'
  get '/index' => 'welcome#index'
  get '/page_404' => 'welcome#page_404', as: :page_404

  get '/articles' => 'welcome#legacy_articles'
  get '/search'   => 'welcome#legacy_search'

  get '/new',  to: redirect('/', status: 301) # 410
  get '/news', to: redirect('/', status: 301)

  get '/authors_articles', to: redirect('/', status: 301)
  get '/blogs.rss', to: redirect('/rss.rss',  status: 301)
  get '/archive',   to: redirect('/archive_numbers', status: 301)
  get '/archives',  to: redirect('/archive_numbers', status: 301)
  get '/partners',  to: redirect('/pages/partners',  status: 301)

  get '/hubs/future', to: redirect('/hubs/future-future', status: 301)

  get '/materia',  to: redirect('http://artelectronics.ru/posts/myslyaschaya-materiya', status: 301)
  get '/materiya', to: redirect('http://artelectronics.ru/posts/myslyaschaya-materiya', status: 301)

  # XML feeds
  get '/feedly.rss'        => 'welcome#feedly',      defaults: { format: :rss }
  get '/novoteka.rss'      => 'welcome#novoteka',      defaults: { format: :rss }
  get '/yandex.rss'        => 'welcome#yandex',        defaults: { format: :rss }
  get '/rss.rss'           => 'welcome#rss',           defaults: { format: :rss }
  get '/rss_full.rss'      => 'welcome#rss_full',      defaults: { format: :rss }
  get '/telegraf_full.rss' => 'welcome#telegraf_full', defaults: { format: :rss }
  get '/rambler.rss'       => 'welcome#rambler',       defaults: { format: :rss }
  get '/surfingbird.rss'   => 'welcome#surfingbird',   defaults: { format: :rss }

  get '/flipboard_culture.rss' => 'welcome#flipboard_culture', defaults: { format: :rss }
  get '/flipboard_tech.rss'    => 'welcome#flipboard_tech',    defaults: { format: :rss }

  get '/sitemap.xml'       => 'welcome#sitemap',       defaults: { format: :xml }

  # Login system
  devise_for :users, path: '',
    :path_names => {
      sign_in:  'login',
      sign_up:  'signup',
      sign_out: 'logout'
    },
    :controllers => {
      :omniauth_callbacks => "omniauth_callbacks",
      :confirmations      => "confirmations",
      :registrations      => "registrations",
      :sessions           => "sessions",
      :passwords          => "passwords"
    }

  devise_scope :user do
    get '/account_should_be_activate' => 'registrations#account_should_be_activate'
  end

  # Personal
  get "cabinet" => "users#cabinet", as: :cabinet

  # Search
  match "search/:squery" => "search#index", via: %w[ get post ], as: :qsearch

  # Special Posts
  post '/tatlin_postcard' => 'special_posts#tatlin_postcard'

  %w[ authors archive_numbers ].each do |model|
    resources model do
      collection do
        get :manage
      end
    end
  end

  get '/authors/:id' => 'authors#show', constraints: {:id => /[^\/]+/}
  get "authors/by/:letter" => "authors#by_letter", as: :author_by_letter

  resources :meta_data

  TheAudit::Routes.mixin(self)
  TheBanners::Routes.mixin(self)

  # Subscribers
  post "subscribers/add" => "subscribers#add", as: :add_subscriber

  namespace :admin do
    TheRole::Routes.mixin(self)
  end

  # TheComments
  concern   :user_comments,  TheComments::UserRoutes.new
  concern   :admin_comments, TheComments::AdminRoutes.new
  resources :comments, concerns:  [:user_comments, :admin_comments]

  concern :sortable_tree do
    collection do
      get  :manage
      post :rebuild
    end
  end

  # legacy url
  get '/blogs/:id' => 'welcome#legacy_blog', constraints: { id: /\d{1,3}/ }

  # Direct routes
  %w{ hubs pages posts blogs }.each do |name|
    resources name, concerns: :sortable_tree do
      get :print

      member do
        patch  :main_image_crop_270x210
        patch  :main_image_crop_100x100
        patch  :main_image_rotate
        delete :main_image_delete
      end
    end
  end

  resources :hubs do
    post :expand_node, on: :collection
  end

  # Users
  resources :users, only: %w[ index show edit update ] do
    patch  :change_email
    patch  :change_password

    patch  :avatar_crop
    delete :avatar_delete

    %w[ hubs pages posts blogs ].each do |name|
      resources name, concerns: :sortable_tree do
        get :my, on: :collection
      end
    end
  end

  # tags
  # tags
  get "tag/:tag" => "tags#show", as: :tag

  # /users/:user_id/manage/posts
  get "manage/:pub_type" => 'posts#manage', as: :pubs_manage
  get "users/:user_id/manage/:pub_type" => 'posts#manage', as: :user_pubs_manage
  get "/:id" => 'hubs#system_section', as: :system_hub

  # Mailer
  get '/rails/mailers' => "rails/mailers#index"
  get '/rails/mailers/*path' => "rails/mailers#preview"

  # Legacy Urls
  get '/:c_slug/:s_slug/:id' => 'welcome#legacy_post'
  get '/:c_slug/:s_slug'     => 'welcome#legacy_hub'
end

app/models/archive_number.rb
class ArchiveNumber < ActiveRecord::Base

  has_attached_file :cover, 
                    styles: { :big => "190x260#", :thumb => "95x122#" }, 
                    default_url: "/default_images/cover/:style/missing.jpg",
                    path: ":rails_root/public/uploads/storages/archive_number/:id/:style/:filename",
                    url: "/uploads/storages/archive_number/:id/:style/:filename"

  do_not_validate_attachment_file_type :cover

end

app/controllers/archive_numbers_controller.rb
class ArchiveNumbersController < ApplicationController
  layout 'bootstrap_default', except: [:index]

  before_action :set_archive_number, only: [ :edit, :update, :show, :destroy ]

  before_action :user_require
  before_action :role_required

  def index
    @archives = ArchiveNumber.all
  end

  def manage
    @archives = ArchiveNumber.all.order(id: :desc).page params[:page]
  end

  def edit; end

  def update
    if @archive.update( archive_params )
        redirect_to archive_numbers_path, notice: t('.updated')
    else
        render action: :edit
    end
  end

  def show; end

  def new
    @archive = ArchiveNumber.new
  end

  def create
    @archive = ArchiveNumber.new( archive_params )

    if @archive.save
      flash.notice = t('.created')
      redirect_to archive_numbers_path
    else
      render action: :new
    end
  end


  def destroy
    @archive.destroy
    redirect_to archive_numbers_url
  end

  private

  def set_archive_number
    @archive = ArchiveNumber.find( params[:id] )
  end

  def archive_params
    params.require(:archive_number).permit(
      :number, :year, :month, :number_in_year,
      :raw_content,
      :cover
    )
  end
end

app/views/bootstrap_default/archive_numbers/_cover.html.haml
.image_toolbar
  .base_view
    %p
      %b= t('.title')

    .image_preview
      = link_to obj.cover.url(:original) do
        = image_tag obj.cover.url(:original)

.form-group
  %p
    %label= t('.select')
    = f.file_field :cover

app/views/bootstrap_default/archive_numbers/_form.html.haml
- content_for :editor do
  %script
    var CKEDITOR_BASEPATH = "/javascripts/ckeditor/";

  = javascript_include_tag "ckeditor/ckeditor"
  = javascript_include_tag "vendors/ckeditor/init"

= form_for @archive, html: { enctype: "multipart/form-data", role: :form } do |f|
  = render partial: 'the_notification/form', locals: { object: @archive }

  .form-group
    = f.label :number, t('.number')
    = f.text_field :number, class: 'form-control'

  .form-group
    = f.label :year, t('.year')
    = f.text_field :year, class: 'form-control'

  .form-group
    = f.label :month, t('.month')
    = f.text_field :month, class: 'form-control'

  .form-group
    = f.label :number_in_year, t('.number_in_year')
    = f.text_field :number_in_year, class: 'form-control'

  .form-group
    = f.label :raw_content, t('.content')
    %br
    = f.text_area :raw_content, class: :redactor_content

  = render partial: 'cover', locals: { f: f, obj: @archive }

  .form-group
    = f.submit 'save', class: 'btn btn-info'

app/views/bootstrap_default/archive_numbers/edit.html.haml
- content_for :express_nav do
  %p= link_to t('admin.archive_numbers.show.title'), archive_number_path( @archive )
  %p= link_to t('admin.archive_numbers.index.title'), archive_numbers_path

%h1= t('.title')
= render 'form'

app/views/bootstrap_default/archive_numbers/index.html.slim
.archives.index
  h1 Архив журнала

  - @archives.each do |archive|
    .issue
      .cover= image_tag archive.cover.url(:big)
      .content= raw archive.raw_content

app/views/bootstrap_default/archive_numbers/manage.html.haml
%h1= t('.title')
%li= link_to t('.link_new'), new_archive_number_path

= paginate @archives

%table.table.table-striped.table-hover
  %thead
    %tr
      %th= t('.number')
      %th= t('.year')
      %th= t('.month')
      %th= t('.number_in_year')
      %th= t('.cover')
  %tbody
    - @archives.each do | archive |
      %tr
        %td= link_to "#{ archive.number }", archive_number_path( archive )
        %td= archive.year
        %td= archive.month
        %td= archive.number_in_year
        %td
          = link_to archive_number_path( archive ) do
            = image_tag archive.cover.url( :thumb )

        %td
          .dropdown
            %button.btn.btn-default.dropdown-toggle(type='button' data-toggle="dropdown")
              %span.caret

            %ul.dropdown-menu(role="menu")
              %li= link_to 'Show', archive_number_path(archive)
              %li= link_to 'Edit', archive_number_path(archive)
              %li= link_to 'Destroy', archive_number_path(archive), method: :delete, data: { confirm: 'Are you sure?' }

= paginate @archives

app/views/bootstrap_default/archive_numbers/new.html.haml
- content_for :express_nav do
  %p= link_to t('admin.archive_numbers.index.title'), archive_numbers_path

%h1= t('.title')
= render 'form'

app/views/bootstrap_default/archive_numbers/show.html.haml
- content_for :express_nav do
  %p= link_to t('.link_edit'), edit_archive_number_path(@archive)
  %p= link_to t('admin.archive_numbers.index.title'), archive_numbers_path

%h1= t('.title')

%table.table
  %tbody
    %tr
      %td
        %strong= "#{t('admin.archive_numbers.form.number')}"
      %td
        = @archive.number

    %tr
      %td
        %strong= "#{t('admin.archive_numbers.form.year')}"
      %td
        = @archive.year

    %tr
      %td
        %strong= "#{t('admin.archive_numbers.form.month')}"
      %td
        = @archive.month

    %tr
      %td
        %strong= "#{t('admin.archive_numbers.form.number_in_year')}"
      %td
        = @archive.number_in_year

    %tr
      %td
        %strong= "#{t('admin.archive_numbers.form.cover')}"
      %td
        = link_to @archive.cover.url( :original ) do
          = image_tag @archive.cover.url( :big )